### ISSUE TITLE
help

### ISSUE THREAD

**Issue by skypin** [alex023/clock#5]
C:\Go\src\github.com\alex023\clock>go test
--- FAIL: TestClock_Create (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recover
ed]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4012ab]

goroutine 5 [running]:
testing.tRunner.func1(0x11978090)
        C:/Go/src/testing/testing.go:711 +0x283
panic(0x506e20, 0x5beb18)
        C:/Go/src/runtime/panic.go:491 +0x1d0
sync/atomic.LoadUint64(0x1195e0a4, 0x1195e090, 0x5d41e0)
        C:/Go/src/sync/atomic/asm_386.s:159 +0xb
github.com/alex023/clock.(*Clock).WaitJobs(0x1195e090, 0x1195e090, 0xfa7b4a21)
        C:/Go/src/github.com/alex023/clock/clock.go:307 +0x26
github.com/alex023/clock.TestClock_Create(0x11978090)
        C:/Go/src/github.com/alex023/clock/clock_test.go:33 +0x33
testing.tRunner(0x11978090, 0x52b240)
        C:/Go/src/testing/testing.go:746 +0xa6
created by testing.(*T).Run
        C:/Go/src/testing/testing.go:789 +0x251
exit status 2
FAIL    github.com/alex023/clock        0.046s

**Comment by alex023** [comment]
I can't reproduce this problem。
## env
macos 10.13.3
go        1.9.2
clock   0.7.4
## input and output
go test -v 
=== RUN   TestClock_Create
--- PASS: TestClock_Create (0.00s)
=== RUN   TestClock_AddOnceJob
--- PASS: TestClock_AddOnceJob (1.01s)
=== RUN   TestJob_Cancel
--- PASS: TestJob_Cancel (5.25s)
=== RUN   TestClock_WaitJobs
--- PASS: TestClock_WaitJobs (10.14s)
=== RUN   TestClock_UpdateJobTimeout
--- PASS: TestClock_UpdateJobTimeout (2.00s)
=== RUN   TestClock_Count
--- PASS: TestClock_Count (1.01s)
=== RUN   TestClock_AddRepeatJob2
--- PASS: TestClock_AddRepeatJob2 (1.01s)
=== RUN   TestClock_AddMixJob
--- PASS: TestClock_AddMixJob (2.00s)
=== RUN   TestClock_AddJobs
--- PASS: TestClock_AddJobs (5.06s)
=== RUN   TestClock_DelJob
--- PASS: TestClock_DelJob (0.18s)
=== RUN   TestClock_DelJobs
--- PASS: TestClock_DelJobs (0.21s)
=== RUN   TestClock_Delay_200kJob
=== RUN   TestClock_Stop
--- PASS: TestClock_Stop (1.01s)
=== RUN   TestClock_StopGracefull
--- PASS: TestClock_StopGracefull (0.02s)
=== RUN   TestRbtree_Insert
--- PASS: TestRbtree_Insert (0.00s)
=== RUN   TestRbtree_Delete
--- PASS: TestRbtree_Delete (0.00s)
=== RUN   ExampleClock_AddJobRepeat
--- PASS: ExampleClock_AddJobRepeat (1.00s)
=== RUN   ExampleClock_AddJobForEvent
--- PASS: ExampleClock_AddJobForEvent (1.00s)
```

Can you tell me, your operating system and the version of the go
