### ISSUE TITLE
服务器重启问题

### ISSUE THREAD

**Issue by luoxiaohui** [alex023/clock#6]
你好，我现在是将所有任务放在一个单例当中，但是当服务器挂了或者重启后，单例中任务都会消失，这种情况应该怎么处理呢？

**Comment by alex023** [comment]
运行时工具，因为值对应的是函数，没法保存。
实际业务中，我们是外部处理的数据加载，加载可能是file、db、redis，根据实际情况来考虑。
比如简单的cron，如果有任务就会写入文件，服务崩掉后，下次加载读取该文件，然后用函数封装对指定程序的调用。

**Comment by luoxiaohui** [comment]
好的，谢谢。
